[lab_academico]
172.26.231.213 ansible_user=lab1
[windows_servers]
172.26.7.217 ansible_user=Administrador
[windows_clients]
172.26.99.50 ansible_user=UsuarioLocal
[macos_clients]
172.26.201.170 ansible_user=lab3

