[linux_clients]
172.26.224.176 ansible_user=carlos
[windows_servers]
172.26.7.217 ansible_user=Administrador
#[windows_clients]
#172.26.99.50 ansible_user=UsuarioLocal
[macos_clients]
172.26.201.170 ansible_user=lab3

